insert into produtos (nome, preco, categoria, tipo, ativo) values
('Promo 2 Lanches', 33.8, 'promocao', 'promocao', true),
('Flag Ship + Fritas', 37.9, 'combos', 'combo', true),
('Flag Ship + Fritas + Coca', 39.9, 'combos', 'combo', true),
('Cheddar Bacon + Fritas', 38.9, 'combos', 'combo', true),
('Cheddar Bacon + Fritas + Coca', 40.9, 'combos', 'combo', true),
('Cebóra + Fritas', 42.9, 'combos', 'combo', true),
('Cebóra + Fritas + Coca', 44.9, 'combos', 'combo', true),
('Cheddar Cremoso + Fritas', 48.9, 'combos', 'combo', true),
('Cheddar Cremoso + Fritas + Coca', 51.9, 'combos', 'combo', true),
('Costeletion + Fritas', 42.9, 'combos', 'combo', true),
('Costeletion + Fritas + Coca', 45.9, 'combos', 'combo', true),
('Ultra Speed + Fritas', 36.9, 'combos', 'combo', true),
('Ultra Speed + Fritas + Coca', 37.9, 'combos', 'combo', true),
('Crazy Burger + Fritas', 43.9, 'combos', 'combo', true),
('Crazy Burger + Fritas + Coca', 45.9, 'combos', 'combo', true),
('Turbo Ultra Speed + Fritas', 44.9, 'combos', 'combo', true),
('Turbo Ultra Speed + Fritas + Coca', 47.9, 'combos', 'combo', true),
('Big Dream + Fritas', 46.9, 'combos', 'combo', true),
('Big Dream + Fritas + Coca', 49.9, 'combos', 'combo', true),
('Speed Max + Fritas', 54.9, 'combos', 'combo', true),
('Speed Max + Fritas + Coca', 57.9, 'combos', 'combo', true),
('Flag Triplo', 43, 'hamburgueres', 'lanche', true),
('Speed Max', 43, 'hamburgueres', 'lanche', true),
('Big Dream', 37, 'hamburgueres', 'lanche', true),
('Crazy Burger', 30, 'hamburgueres', 'lanche', true),
('Cheddar Bacon', 29, 'hamburgueres', 'lanche', true),
('Costeletion', 34, 'hamburgueres', 'lanche', true),
('Cebóra', 32, 'hamburgueres', 'lanche', true),
('Cheddar Cremoso c/ Bacon', 37, 'hamburgueres', 'lanche', true),
('Pepeburger', 25, 'hamburgueres', 'lanche', true),
('Turbo Ultra Speed', 32, 'hamburgueres', 'lanche', true),
('Flag Ship', 27, 'hamburgueres', 'lanche', true),
('Cheese Bacon', 22, 'hamburgueres', 'lanche', true),
('Ultra Speed', 22, 'hamburgueres', 'lanche', true),
('Speed Duplo', 30, 'fast-food', 'lanche', true),
('Speed Chicken', 20, 'fast-food', 'lanche', true),
('Speed Burger', 20, 'fast-food', 'lanche', true),
('Speed Simples', 20, 'fast-food', 'lanche', true),
('Cebola empanada', 26, 'porcoes', 'porcao', true),
('Fritas + Coca', 14.9, 'porcoes', 'porcao', true),
('Batata meia + 2 coca', 21.9, 'porcoes', 'porcao', true),
('Fritas pequena', 12, 'porcoes', 'porcao', true),
('Fritas média', 18, 'porcoes', 'porcao', true),
('Fritas grande', 22, 'porcoes', 'porcao', true),
('Batata cheddar bacon meia', 24, 'porcoes', 'porcao', true),
('Batata cheddar bacon inteira', 32, 'porcoes', 'porcao', true),
('Dell Laranja 450ml', 6, 'bebidas', 'bebida', true),
('Dell Uva 450ml', 6, 'bebidas', 'bebida', true),
('Água', 4, 'bebidas', 'bebida', true),
('Sprite 350ml', 6, 'bebidas', 'bebida', true),
('Coca Cola 350ml', 7, 'bebidas', 'bebida', true),
('Coca Cola 2L', 15, 'bebidas', 'bebida', true),
('Fanta Laranja 350ml', 6, 'bebidas', 'bebida', true),
('Mini Coca 200ml', 3, 'bebidas', 'bebida', true),
('Schweppes 350ml', 6, 'bebidas', 'bebida', true),
('Nuggets (6 un)', 12.9, 'complementos', 'complemento', true),
('Cheddar cremoso c/ bacon', 8.9, 'complementos', 'complemento', true);
